name: Build Full Stack Application

on:
  push:
    branches:
      - main
      - test
  pull_request:
    branches:
      - main
      - test

jobs:
  # Backend Job
  build-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/spring-boot-ecommerce

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # Update to your project's Java version

      - name: Build Backend with Maven
        run: mvn clean install

      - name: Run Backend Tests
        run: mvn test

  # Frontend Job
  build-frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend/angular-ecommerce

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Update to your project's Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Build Frontend
        run: npm run build
